spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${AUTH_SERVICE_POSTGRES_DB}
    username: ${AUTH_SERVICE_POSTGRES_USER}
    password: ${AUTH_SERVICE_POSTGRES_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  accessTokenExpirationMinutes: ${JWT_ACCESS_EXP_MINUTES}
  refreshTokenExpirationDays: ${JWT_REFRESH_EXP_DAYS}


