spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
    listener:
      auto-startup: false
    consumer:
      group-id: user-profile-test
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "korobkin.nikita.events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: test-secret
  issuer: test
  access-token-expiration-minutes: 1
  refresh-token-expiration-days: 1

auth:
  cookie:
    name: refreshToken
    http-only: true
    secure: false
    same-site: None
    path: /api/auth
    max-age-days: 7

