spring:
  datasource:
    url: jdbc:postgresql://user_profile_postgres:5432/${PROFILE_SERVICE_POSTGRES_DB}
    username: ${PROFILE_SERVICE_POSTGRES_USER}
    password: ${PROFILE_SERVICE_POSTGRES_PASSWORD}

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

services:
  media-service:
    url: ${MEDIA_SERVICE_URL}
