spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  kafka:
    consumer:
      group-id: user-profile-group
      auto-offset-reset: earliest

app:
  kafka:
    topics:
      user-created: user-created
