spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/profile_service
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: localhost:9094

server:
  port: 8082

jwt:
  secret: my-dev-secret
  issuer: dev-issuer
