spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  kafka:
    consumer:
      group-id: project-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "korobkin.nikita.events"
        spring.json.value.default.type: korobkin.nikita.events.ProjectSkillVerificationRequestedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topics:
      project-skill-verification-requested: project.skill.verification.requested
      project-skill-verification-completed: project.skill.verification.completed
