services:
  auth_postgres:
    image: postgres:16-alpine
    container_name: auth_postgres
    environment:
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  user_profile_postgres:
    image: postgres:16-alpine
    container_name: user_profile_postgres
    environment:
      POSTGRES_USER: ${PROFILE_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROFILE_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROFILE_SERVICE_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - user_profile_postgres_data:/var/lib/postgresql/data

  skill_postgres:
    image: postgres:16-alpine
    container_name: skill_postgres
    environment:
      POSTGRES_USER: ${SKILL_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SKILL_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SKILL_SERVICE_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - skill_postgres_data:/var/lib/postgresql/data

  project_postgres:
    image: postgres:16-alpine
    container_name: project_postgres
    environment:
      POSTGRES_USER: ${PROJECT_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROJECT_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROJECT_SERVICE_POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - project_postgres_data:/var/lib/postgresql/data

  skill_verification_postgres:
    image: postgres:16-alpine
    container_name: skill_verification_postgres
    environment:
      POSTGRES_USER: ${SKILL_VERIFICATION_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SKILL_VERIFICATION_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SKILL_VERIFICATION_SERVICE_POSTGRES_DB}
    ports:
      - "5436:5432"
    volumes:
      - skill_verification_postgres_data:/var/lib/postgresql/data

  portfolio_postgres:
    image: postgres:16-alpine
    container_name: portfolio_postgres
    environment:
      POSTGRES_USER: ${PORTFOLIO_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PORTFOLIO_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PORTFOLIO_SERVICE_POSTGRES_DB}
    ports:
      - "5437:5432"
    volumes:
      - portfolio_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: auth_redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8087:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data

  auth-service:
    build:
      context: ./auth-service
    image: coldsteeze/auth-service:latest
    depends_on:
      - auth_postgres
      - redis
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AUTH_SERVICE_POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      AUTH_SERVICE_POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
      AUTH_SERVICE_POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_ACCESS_EXP_MINUTES: ${JWT_ACCESS_EXP_MINUTES}
      JWT_REFRESH_EXP_DAYS: ${JWT_REFRESH_EXP_DAYS}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      HTTP_ONLY: ${HTTP_ONLY}
      SECURE: ${SECURE}
      SAME_SITE: ${SAME_SITE}
      MAX_AGE_DAYS: ${MAX_AGE_DAYS}
    ports:
      - "8081:8080"

  user-profile-service:
    build:
      context: ./user-profile-service
    image: coldsteeze/user-profile-service:latest
    depends_on:
      - user_profile_postgres
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      PROFILE_SERVICE_POSTGRES_USER: ${PROFILE_SERVICE_POSTGRES_USER}
      PROFILE_SERVICE_POSTGRES_PASSWORD: ${PROFILE_SERVICE_POSTGRES_PASSWORD}
      PROFILE_SERVICE_POSTGRES_DB: ${PROFILE_SERVICE_POSTGRES_DB}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
    ports:
      - "8082:8080"

  skill-service:
    build:
      context: ./skill-service
    image: coldsteeze/skill-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SKILL_SERVICE_POSTGRES_USER: ${SKILL_SERVICE_POSTGRES_USER}
      SKILL_SERVICE_POSTGRES_PASSWORD: ${SKILL_SERVICE_POSTGRES_PASSWORD}
      SKILL_SERVICE_POSTGRES_DB: ${SKILL_SERVICE_POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
    ports:
      - "8083:8080"

  project-service:
    build:
      context: ./project-service
    image: coldsteeze/project-service:latest
    depends_on:
      - project_postgres
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      PROJECT_SERVICE_POSTGRES_USER: ${PROJECT_SERVICE_POSTGRES_USER}
      PROJECT_SERVICE_POSTGRES_PASSWORD: ${PROJECT_SERVICE_POSTGRES_PASSWORD}
      PROJECT_SERVICE_POSTGRES_DB: ${PROJECT_SERVICE_POSTGRES_DB}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      SKILL_SERVICE_URL: ${SKILL_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      PROJECT_IMAGES_MAX_COUNT: ${PROJECT_IMAGES_MAX_COUNT}
    ports:
      - "8084:8080"

  skill-verification-service:
    build:
      context: ./skill-verification-service
    image: coldsteeze/skill-verification-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SKILL_VERIFICATION_SERVICE_POSTGRES_USER: ${SKILL_VERIFICATION_SERVICE_POSTGRES_USER}
      SKILL_VERIFICATION_SERVICE_POSTGRES_PASSWORD: ${SKILL_VERIFICATION_SERVICE_POSTGRES_PASSWORD}
      SKILL_VERIFICATION_SERVICE_POSTGRES_DB: ${SKILL_VERIFICATION_SERVICE_POSTGRES_DB}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "0:8080"

  portfolio-service:
    build:
      context: ./portfolio-service
    image: coldsteeze/portfolio-service:latest
    depends_on:
      - portfolio_postgres
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      PORTFOLIO_SERVICE_POSTGRES_USER: ${PORTFOLIO_SERVICE_POSTGRES_USER}
      PORTFOLIO_SERVICE_POSTGRES_PASSWORD: ${PORTFOLIO_SERVICE_POSTGRES_PASSWORD}
      PORTFOLIO_SERVICE_POSTGRES_DB: ${PORTFOLIO_SERVICE_POSTGRES_DB}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
    ports:
      - "8085:8080"

  media-service:
    build:
      context: ./media-service
    image: coldsteeze/media-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MINIO_URL: ${MINIO_URL}
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
    ports:
      - "8086:8080"

  gateway-service:
    build:
      context: ./gateway-service
    image: coldsteeze/gateway-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AUTH_SERVICE_URI: ${AUTH_SERVICE_URI}
      USER_PROFILE_SERVICE_URI: ${USER_PROFILE_SERVICE_URI}
      SKILL_SERVICE_URI: ${SKILL_SERVICE_URI}
      PROJECT_SERVICE_URI: ${PROJECT_SERVICE_URI}
      PORTFOLIO_SERVICE_URI: ${PORTFOLIO_SERVICE_URI}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_PUBLIC_ENDPOINTS: ${JWT_PUBLIC_ENDPOINTS}
    ports:
      - "8080:8080"


volumes:
  auth_postgres_data:
  user_profile_postgres_data:
  skill_postgres_data:
  project_postgres_data:
  skill_verification_postgres_data:
  portfolio_postgres_data:
  minio_data:
  kafka_data:
    driver: local
