services:
  auth-service-uri: http://localhost:8081
  user-profile-service-uri: http://localhost:8082

cors:
  frontend-url: http://localhost:63342

jwt:
  secret: my-dev-secret
  issuer: dev-issuer
  public-endpoints:
    - /api/auth/login
    - /api/auth/register