services:
  auth-service-uri: ${AUTH_SERVICE_URI}
  user-profile-service-uri: ${USER_PROFILE_SERVICE_URI}
  skill-service-uri: ${SKILL_SERVICE_URI}
  project-service-uri: ${PROJECT_SERVICE_URI}

cors:
    frontend-url: ${FRONTEND_URL}

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  public-endpoints: ${JWT_PUBLIC_ENDPOINTS}