spring:
  datasource:
    url: jdbc:postgresql://skill_postgres:5432/${SKILL_SERVICE_POSTGRES_DB}
    username: ${SKILL_SERVICE_POSTGRES_USER}
    password: ${SKILL_SERVICE_POSTGRES_PASSWORD}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}