spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  kafka:
    consumer:
      group-id: project-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topics:
      project-skill-verification-requested: project.skill.verification.requested
      project-skill-verification-completed: project.skill.verification.completed
      project-created: project-created
      project-updated: project-updated
      project-deleted: project-deleted
      project-skill-added: project-skill-added
      project-skill-removed: project-skill-removed
