spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/project_service
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: localhost:9094

server:
  port: 8084

jwt:
  secret: my-dev-secret
  issuer: dev-issuer

skill-service:
  base-url: http://localhost:8080
  path: /api/skills